name: build-progress

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: Jeric-X/SyncClipboard
        ref: avalonia

    # Install the .NET workload
    - name: Install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Install dependencies
      working-directory: ./src
      run: dotnet restore

    - name: Check code style
      working-directory: ./src
      run: dotnet format --verify-no-changes --no-restore

    - name: Check code style info
      working-directory: ./src
      run: |
        dotnet format --severity info --verify-no-changes --no-restore
        exit 0

    - name: Build linux 
      run: msBuild src/SyncClipboard.Desktop/SyncClipboard.Desktop.csproj /p:Configuration=Release /t:Publish /v:m /p:Platform=x64 /p:RuntimeIdentifier=linux-x64 /p:SelfContained=false

    - name: copy linux 
      run: xcopy src/SyncClipboard.Desktop/bin/x64/Release/net6.0/linux-x64/publish linux\ /s /e

    - name: Generate change log
      run: |
        .\PreRelease.bat
        type feature.txt

    - name: Upload build artifacts SyncClipboard.WinUI3
      uses: actions/upload-artifact@v3
      with:
        name: SyncClipboard.linux
        path: linux/

    - name: Upload change log
      uses: actions/upload-artifact@v3
      with:
        name: feature
        path: feature.txt