name: linux-package

permissions:
  contents: write

on:
  push:
    branches:
      - '**'
    tags-ignore: 
      - 'v*'
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build-progress.yml

  package:
    strategy:
      matrix:
        cpu: [x64]
        type: [self-contained, no-self-contained]
        # include:
        #   - package-type: AppImage
        #     package-head: SyncClipboard-
        #     package-tail: .x86_64
        #   - package-type: rpm
        #     package-head: syncclipboard_
        #     package-tail: .x86_64
        #   - package-type: deb
        #     package-head: syncclipboard_
        #     package-tail: _amd64

    runs-on: macos-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: Jeric-X/SyncClipboard
          ref: avalonia

      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Download last-job-built artifact
        uses: actions/download-artifact@v3
        with:
          name: osx-${{ matrix.cpu }}-${{ matrix.type }}
          path: macos-bin/

      - name: Download version
        uses: actions/download-artifact@v3
        with:
          name: version
          path: ./

      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version.txt

      - name: Package
        run: ./buildAppBundle.sh 
        working-directory: ./build/macos

      - name: Upload build artifacts ${{ matrix.type }}
        uses: actions/upload-artifact@v3
        with:
          name: SyncClipboard_${{ steps.version.outputs.content }}_${{ matrix.type }}
          path: build/macos/SyncClipboard.app/

