name: package

permissions:
  contents: write

on:
  push:
    branches:
      - '**'
    tags: 
      - 'v*'
  pull_request:

jobs:
  linux:
    uses: Jeric-X/SyncClipboard/.github/workflows/linux-release.yml@ci
    with:
      checkout-repo: 'Jeric-X/SyncClipboard'
      checkout-ref: 'ci'

  mac:
    uses: Jeric-X/SyncClipboard/.github/workflows/mac-release.yml@ci
    with:
      checkout-repo: 'Jeric-X/SyncClipboard'
      checkout-ref: 'ci'