name: package

permissions:
  contents: write

on:
  push:
    branches:
      - '**'
    tags: 
      - 'v*'
  pull_request:

jobs:
  build:
    uses: Jeric-X/SyncClipboard/.github/workflows/desktop-package.yml@avalonia
    with:
      checkout-repo: 'Jeric-X/SyncClipboard'
      checkout-ref: 'master'